### ISSUE TITLE
[PE-D][Tester B] Typo in user guide for rate

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T12-3/tp#149]
User guide shows example for adding a review with prefix r/ instead of re/:

![image.png](https://raw.githubusercontent.com/farisanadia/ped/main/files/a0b1394a-c9f3-4fa2-8c5c-c8f653486901.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: farisanadia/ped#3

**Comment by ngquyduc** [comment]
Same issue as #147
