### ISSUE TITLE
[PE-D][Tester C] select command not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T12-3/tp#157]
![image.png](https://raw.githubusercontent.com/nopehax/ped/main/files/03ef9384-61bd-40b8-b228-af0bf1ef0844.png)
select command isn't working after running other commands. Pressing enter doesn't do anything, no invalid/valid command result

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nopehax/ped#2

**Comment by ngquyduc** [comment]
Fix together with #152
