### ISSUE TITLE
[PE-D][Tester E] Review field in rate command accepted Special symbol

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T12-3/tp#163]
Review field in rate command accepted Special symbol. Not sure if field is suppose to accept special symbol but was not stated in UG.
![image.png](https://raw.githubusercontent.com/tanxuanyun/ped/main/files/caa9b90c-1c8c-4e8f-a2e6-f8b8d28cf9b4.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: tanxuanyun/ped#2

**Comment by ngquyduc** [comment]
I don't think this is an issue. May be better documentation would clear the doubts.
