### ISSUE TITLE
[PE-D][Tester E] Renaming command allow special symbol 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T12-3/tp#185]
Renaming of command allowed special symbol not sure if it is allowed by not stated in the UG.

![image.png](https://raw.githubusercontent.com/tanxuanyun/ped/main/files/ffe0b7e4-1cc4-4afd-9042-397f57415165.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: tanxuanyun/ped#9

**Comment by ngquyduc** [comment]
Update the UG

**Comment by ngquyduc** [comment]
The UG is updated.
