### ISSUE TITLE
[PE-D][Tester D] Edit activity with same value as before

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T12-3/tp#186]
Action: used edit 3 d/d on an activity which description was already "d".

![image.png](https://raw.githubusercontent.com/phualiting/ped/main/files/83147f7c-0b1c-4a80-8e48-1e30a219c694.png)

I think it doesn't make much sense to return the message that activity was edited, since the activity did not change.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: phualiting/ped#11

**Comment by ZhengLong3** [comment]
Check if activity has been altered in edit command, then output the relevant message
